[project]
name = "tele-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.0.7",
    "langchain-ollama>=1.0.0",
    "ollama>=0.6.1",
    "python-decouple>=3.8",
    "python-telegram-bot>=22.5",
]
